pagu-project/pagu

- README.md
- client/client.go
- client/client_mgr.go
- client/interface.go
- client/mock.go
- engine/engine.go
- engine/engine_test.go
- engine/interface.go
- store/interface.go
- store/mock.go
- store/store.go
- store/store_test.go
> feat: adding claim command to bot engine

- scripts/python/main.py
- scripts/python/network.py
Script for final reward calc on testnet campaigns
> feat(script): final reward calculation for test-net 1 and 2

- discord/commands.go
- discord/discord.go
- discord/embeds.go
- discord/handlers.go
> feat: adding more features to discord module

- client/client_mgr.go
- engine/engine.go
- engine/engine_test.go
This PR fixes the local node and claim tests
> fix: failing tests

- twitter_api/twitter.go
This PR Updates the Twitter query string
> fix: update twitter query

- engine/engine.go
- store/store.go
- store/store_test.go
> fix(engine): case insensitive check in finding twitter username

- engine/engine.go
- twitter_api/twitter.go
> chore: Typos Fixed

- database/database.go
- database/database_test.go
- database/tables.go
- engine/commands.go
- engine/engine.go
- go.mod
> feat: implement create offer

- Makefile
- engine/utils.go
- engine/utils_test.go
This PR fixes the booster price for package above 400
> fix: booster price for packages after 400

- cmd/cli/main.go
- cmd/discord/main.go
- version.go
> feat: addign version.go file for version management

- client/client.go
- client/client_mgr.go
- client/interface.go
- client/mock.go
- cmd/cli/main.go
- cmd/grpc/main.go
- engine/command/blockchain/blockchain.go
- engine/engine.go
- grpc/robopac.go
> feat: adding fee sub command to blockchain

- config/config.go
- discord/discord.go
- engine/command/phoenix/phoenix.go
- engine/engine.go
- go.mod
- go.sum
- version.go
> fix(discord): supporting subcommands

- database/database.go
- database/database_test.go
- database/tables.go
- engine/command/zealy/zealy.go
- engine/engine.go
- wallet/wallet.go
> feat: zealy command

- internal/engine/command/voucher/claim_test.go
- internal/engine/command/voucher/status.go
- internal/engine/command/voucher/status_test.go
- internal/engine/command/voucher/voucher.go
- internal/repository/faucet.go
- internal/repository/interface.go
- internal/repository/mock.go
- internal/repository/user.go
- internal/repository/voucher.go
- internal/repository/zealy.go
This PR includes a new command to show the status of vouchers. This command has an optional parameter "code" that indicates the result must show the status of one specific code or all codes.
> feat(voucher): add status command

- .golangci.yml
- README.md
- config/config-sample.yml
- internal/engine/command/command.go
README.md file updated to make better contribution
> docs(readme): README.md file updated

- internal/engine/command/market/market.go
- internal/engine/command/market/price.go
- internal/entity/price.go
- internal/job/price.go
In this PR the Azbit market price added into `/market price` command. Also Exbitron market removed.
- Fixes #(issue number)
> feat(market): add Azbit market price and remove exbitron

- internal/engine/command/zealy/zealy.go
- internal/engine/engine.go
- pkg/client/mock.go
In this PR the zealy command activated on Discord platform
> feat(zealy): active zealy command

- INSTALL.md
- README.md
This PR updates the README and INSTALL documents.
> chore: update readme and install

- .github/workflows/deploy.yml
Set environment variable properly for deployment.
> ci: set environment variables properly

- deployment/docker-compose.yml
This PR formats the docker-compose YAML file.
> chore: format YAML file

- .github/workflows/deploy.yml
This PR removes the enthronement variables from deploy action. 
- Fixes #(issue number)
> ci: remove environment variables from deploy action

- internal/engine/command/command.go
- internal/platforms/discord/discord.go
- internal/platforms/discord/utils.go
- pkg/color/color.go
Define the color code to add more flexibility in future use.
> feat: define color codes

- internal/platforms/discord/discord.go
fix: argument parse issue on discord
> fix: argument parse issue on discord

- internal/engine/engine.go
[](feat: add log on parse and execute)
> feat: add log on parse and execute

- deployment/README.md
- version.go
chore: remove meta from versioning
> chore: remove meta from versioning

- internal/engine/command/voucher/create_test.go
- internal/repository/mock.go
- pkg/client/client.go
- pkg/client/client_mgr.go
- pkg/client/client_mgr_test.go
- pkg/client/interface.go
- pkg/client/mock.go
- pkg/wallet/mock.go
This PR updates client log to prevent massive logs on fetching network information.
> chore: update client log

- .gitignore
- deployment/docker-compose.yml
- internal/entity/faucet.go
- internal/entity/model.go
- internal/entity/user.go
- internal/entity/voucher.go
- internal/entity/zealy.go
This PR updates the column tags for gorm.
> fix: fix database column attributes

- internal/repository/user.go
This PR fixes the user query issue after updating users table.
> fix: get-user query issue

- internal/repository/user.go
Remove debug lines and revert #224
> chore: remove debug lines

- version.go
> chore: update version to 0.0.3

- .golangci.yml
- internal/entity/price.go
- pkg/utils/ip.go
This PR enables tagliatelle linter for checking JSON tags.
> chore: enable tagliatelle linter

- .golangci.yml
- internal/engine/command/command.go
- internal/engine/command/crowdfund/config.go
- internal/engine/command/crowdfund/crowdfund.go
- internal/engine/command/crowdfund/crowdfund_test.go
- internal/engine/command/crowdfund/info.go
- internal/engine/command/crowdfund/info_test.go
- internal/engine/engine.go
- internal/entity/crowdfund.go
- internal/repository/crowdfund.go
This PR implements `Crowdfund:info` command
- Fixes #185
> feat: implement crowdfund:info command

- deployment/README.md
- deployment/deploy.sh
- deployment/docker-compose.db.yml
- deployment/docker-compose.yml
This PR deploy Pagu for both stable and latest versions.
- Fixes #217
> ci: separate deployment process for stable and latest versions

- internal/engine/command/crowdfund/create.go
- internal/entity/crowdfund.go
This PR adds the `CreatorID` for the `CrowdfundCampign` record
> fix: CreatorID for CrowdfundCampaign record

- cmd/cli/main.go
- config/config.go
- internal/engine/command/calculator/reward.go
- internal/engine/command/network/node_info.go
- internal/engine/command/network/status.go
- internal/engine/command/voucher/create.go
- internal/job/notification.go
- internal/platforms/discord/discord.go
- internal/platforms/telegram/telegram.go
- pkg/client/client_mgr.go
- pkg/nowpayments/nowpayments.go
- pkg/utils/utils.go
This PR refactors the import paths and reduce dependencies to Pactus project.
> refactor: refactor import paths

- internal/engine/command/calculator/calculator.go
- internal/engine/command/command.go
- internal/engine/command/crowdfund/crowdfund.go
- internal/engine/command/voucher/voucher.go
- internal/platforms/discord/discord.go
This PR support choices for command argument.
> feat: support choices for arguments

- version.go
> chore: bump version to 0.0.4

- internal/engine/command/calculator/calculator.go
- internal/engine/command/command.go
- internal/engine/command/crowdfund/crowdfund.gen.go
- internal/engine/command/crowdfund/crowdfund.go
- internal/engine/command/crowdfund/crowdfund.yml
- internal/engine/command/market/market.go
- internal/engine/command/network/network.go
- internal/engine/command/phoenix/phoenix.go
- internal/engine/command/voucher/voucher.go
- internal/engine/command/zealy/zealy.go
- internal/platforms/telegram/telegram.go
Ensure choices set to argument once created.
> fix: ensure choices set to argument

- Makefile
- internal/engine/command/crowdfund/create_test.go
- internal/engine/command/crowdfund/crowdfund.gen.go
- internal/engine/command/crowdfund/crowdfund.go
- internal/engine/command/crowdfund/info_test.go
- internal/engine/command/crowdfund/purchase_test.go
- internal/generator/command.tmpl
Refactor template and update the AppID and Flags for crowdfund command.
> fix: set proper AppIDs and Flags

- internal/engine/command/crowdfund/crowdfund.go
- internal/engine/command/crowdfund/purchase.go
- internal/engine/command/crowdfund/purchase_test.go
Prevent panic when user select invalid package number.
> fix: prevent panic on invalid package number

- pkg/nowpayments/nowpayments.go
Invalid JSON data for NowPayments API.
> fix: invalid JSON data

- internal/engine/command/crowdfund/crowdfund.gen.go
- internal/engine/command/crowdfund/crowdfund.go
- internal/engine/command/crowdfund/crowdfund.yml
- internal/engine/command/crowdfund/purchase.go
- internal/engine/engine.go
- pkg/nowpayments/nowpayments.go
This PR removes the Zealy command.
> feat: remove zealy command

- version.go
> chore: bump version to 0.0.5

- INSTALL.md
- config/config.sample.yml
Updating INSTALL.md with an example for `calculate reward` command.
> docs: update INSTALL.md

- internal/engine/command/voucher/claim.go
- internal/engine/command/voucher/create.go
- internal/engine/command/voucher/create_test.go
- internal/engine/command/voucher/voucher.go
fix: check voucher code expiry
In the condition for checking the expiration time of a code, the validity period in months should be added to the code's creation time. Then, compare it to the current time. If it is earlier than the current time, an error should be returned to the user.
> fix: check voucher code expiry

- internal/engine/command/command.go
- internal/engine/command/market/market.gen.go
This PR adds emoji for Help and About and fix failed status for help command.
> fix: fix failed status for help command

- internal/engine/command/market/market.yml
link Xeggex to https://xeggex.com/market/PACTUS_USDT 
link Azbit to https://azbit.com/exchange/PAC_USDT
> style: link word to web link .

- internal/platforms/telegram/telegram.go
fix help and about command in telegram bot .
> fix: help and about command in telegram bot .

- internal/engine/command/command.go
Change about emoji in order to display it better in platforms
> fix: about emoji

- internal/version/version.go
> chore: bump version to 0.0.8

- internal/engine/command/calculator/calculator.go
- internal/engine/command/command.go
- internal/engine/command/crowdfund/crowdfund.go
- internal/engine/command/market/market.go
- internal/engine/command/network/network.go
- internal/engine/command/phoenix/phoenix.go
- internal/engine/command/voucher/voucher.go
- internal/engine/command/zealy/zealy.go
- internal/engine/engine.go
- internal/entity/application.go
- internal/platforms/discord/discord.go
- internal/platforms/telegram/telegram.go
- internal/repository/user.go
> refactor: rename appID to platformID

- internal/platforms/telegram/telegram.go
fix show mark down messages in telegram correctly .
> fix: show markdowns correctly in telegram .

- deployment/docker-compose.yml
Update docker-compoer deployment file.
> ci: update docker-composer file

- internal/engine/command/phoenix/phoenix.gen.go
- internal/engine/command/phoenix/phoenix.yml
Fix invalid link to Pacviewer for faucet transactions.
> fix: fix faucet transaction link

- internal/version/version.go
> feat: bump patch version to v0.0.9

- internal/platforms/telegram/telegram.go
each subcommand has owne help and show it correctly .
> fix: each subcommand has owne help .

- INSTALL.md
- internal/platforms/cli/cli.go
Format result on CLI using glow
> style: format result on cli using glow

- config/config.go
- internal/engine/command/voucher/create.go
- internal/engine/command/zealy/claim.go
- internal/engine/engine_test.go
- internal/platforms/telegram/telegram.go
> feat: add telegram choices

- internal/version/version.go
> chore: bump minor version to v0.1.0

- internal/engine/command/market/market.gen.go
- internal/engine/command/market/market.yml
- internal/engine/command/market/price.go
- internal/job/price.go
> feat:  add xeggex price .

- internal/version/version.go
> chore: bump patch version to v0.1.1

- deployment/README.md
- deployment/docker2host.service
- deployment/docker2host.sh
- docs/port-forwarding.md
This PR adds documentation for port-forwarding.
> chore: add documentation for docker2host service

- internal/platforms/discord/discord.go
remove a condition about discord direct message
> refactor: remove a condition about discord direct message.

- internal/platforms/discord/discord.go
> revert: "refactor: remove a condition about discord direct message."

- internal/engine/command/crowdfund/crowdfund.go
Fix a mistake on getting last campaign.
> fix: last campaign issue

- internal/engine/command/crowdfund/edit_test.go
- internal/platforms/discord/discord.go
Add test to check enabling crowdfund campaign.
> test: add test for enabling crowdfund campaign

- internal/platforms/discord/discord.go
Fix the issue of: "StringValue called on data option of type Boolean"
> fix(discord): fix bool val issue

- internal/version/version.go
> chore: bump patch version to v0.1.2

- internal/platforms/whatsapp/whatsapp.go
> feat: use net http instead of fiber

- internal/platforms/whatsapp/whatsapp.go
- pkg/session/session.go
- pkg/session/session_manager_test.go
add new session function
https://github.com/pagu-project/pagu/issues/371
https://github.com/pagu-project/pagu/issues/372
> feat: add new session function

- config/config.go
- config/config.sample.yml
- go.mod
- go.sum
- internal/platforms/whatsapp/whatsapp.go
- pkg/session/session.go
> feat: make code logic simpler . 

- internal/engine/command/command.go
- internal/engine/command/network/health.go
- internal/platforms/telegram/telegram.go
- pkg/client/client.go
- pkg/client/client_mgr.go
- pkg/client/interface.go
- pkg/client/mock.go
This PR updates the About command.
> fix: update and fix commands issues

- internal/engine/command/command.go
- internal/engine/command/phoenix/faucet.go
This PR updates the invalid address error for better clarity.
> fix: update faucet error message

- internal/engine/command/crowdfund/crowdfund.gen.go
- internal/engine/command/crowdfund/crowdfund.yml
- internal/platforms/telegram/telegram.go
This PR fixes an issue where the TG result was not displayed.
> fix: fix TG command issue

- pkg/client/client_mgr.go
This PR checks `updateValMap` using goroutine to start the Bot faster.
> fix: start the bot faster using goroutine

- docs/contributing.md
- docs/debugging.md
- docs/getting-started.md
- internal/config/config.sample.yml
- internal/platforms/whatsapp/config.go
- internal/platforms/whatsapp/whatsapp.go
> docs: update docs

- pkg/markdown/telegram_renderer.go
- pkg/markdown/telegram_renderer_test.go
- pkg/markdown/whatsapp_renderer.go
Fix MD link issue on TG (check tests)
> fix: fix MD renderer in TG

- internal/engine/command/voucher/claim.go
- internal/engine/engine.go
- internal/job/price.go
- internal/platforms/discord/discord.go
- internal/platforms/grpc/server.go
- internal/platforms/telegram/telegram.go
- internal/platforms/whatsapp/whatsapp.go
- internal/repository/voucher.go
- pkg/client/client_mgr.go
- pkg/mailer/smtp.go
- pkg/markdown/cli_renderer.go
- pkg/wallet/wallet.go
This PR fixes log issues and set proper key/values.
> refactor: fix log issues

- go.mod
- go.sum
- internal/cmd/pagu.go
- internal/config/config.go
- internal/engine/command/calculator/fee.go
- internal/engine/command/calculator/reward.go
- internal/engine/command/network/node_info.go
- internal/engine/command/voucher/claim.go
- internal/engine/command/voucher/create.go
- internal/engine/command/voucher/create_bulk.go
- internal/engine/command/voucher/create_bulk_test.go
- internal/engine/command/voucher/status.go
- internal/engine/command/voucher/status_test.go
- internal/engine/command/voucher/voucher.gen.go
- internal/engine/command/voucher/voucher.go
- internal/engine/command/voucher/voucher.yml
- internal/engine/engine.go
- internal/entity/application.go
- internal/platforms/discord/discord.go
- internal/platforms/telegram/telegram.go
- pkg/client/client_mgr.go
- pkg/mailer/smtp.go
- pkg/utils/utils.go
This PR adds `create-bulk` sub-command for voucher.
> feat(voucher): add create-bulk command

- internal/engine/command/voucher/create.go
- internal/engine/command/voucher/create_bulk.go
- internal/engine/command/voucher/create_test.go
- internal/engine/command/voucher/report.go
- internal/engine/command/voucher/status.go
- internal/engine/command/voucher/status_test.go
- internal/engine/command/voucher/voucher.gen.go
- internal/engine/command/voucher/voucher.yml
- internal/entity/voucher.go
- internal/repository/voucher.go
This PR adds `report` sub-command for `voucher`.
> feat(voucher): add report command

- internal/engine/command/voucher/create.go
> chore: add logs for creating voucher

- internal/engine/command/market/market.go
- internal/engine/command/market/price.go
- internal/engine/command/network/health.go
- internal/engine/command/network/network.gen.go
- internal/engine/command/network/network.go
- internal/engine/command/network/network.yml
- internal/engine/command/network/node_info.go
- internal/engine/command/network/status.go
- internal/engine/command/network/wallet.go
- internal/engine/command/phoenix/phoenix.gen.go
- internal/engine/command/phoenix/phoenix.yml
- internal/engine/command/voucher/claim.go
- internal/engine/command/voucher/create.go
- internal/engine/command/voucher/create_bulk.go
- internal/engine/command/voucher/report.go
- internal/engine/command/voucher/status.go
- internal/engine/command/voucher/voucher.go
- internal/engine/engine.go
Adds the `wallet` subcommand for `network` command
> feat: add wallet subcommand for network

- internal/version/version.go
> chore: update version to 0.2.0

- internal/version/version.go
> chore: bump version to 0.3.0

- pkg/mailer/interface.go
- pkg/mailer/mock.go
- pkg/mailer/smtp.go
This PR adds the email into log message.
> chore: add email in log message

- internal/engine/command/voucher/create.go
- internal/engine/command/voucher/create_bulk.go
- internal/engine/command/voucher/create_test.go
- internal/engine/command/voucher/voucher.gen.go
- internal/engine/command/voucher/voucher.yml
This PR resend the voucher email if it is not claimed yet.
> feat: resend the voucher email

- internal/engine/command/market/market.gen.go
- internal/engine/command/market/market.yml
- internal/engine/command/market/price.go
- internal/entity/price.go
- internal/job/price.go
> fix: remove xeggex

- internal/engine/command/voucher/create_test.go
- internal/repository/voucher.go
`desc` is a reserved keyword in SQL
> fix: fix SQL issue

- internal/version/version.go
> chore: bump version to 0.4.0

- internal/engine/command/calculator/calculator.gen.go
- internal/engine/command/command.go
- internal/engine/command/crowdfund/crowdfund.gen.go
- internal/engine/command/crowdfund/crowdfund.yml
- internal/engine/command/market/market.gen.go
- internal/engine/command/network/network.gen.go
- internal/engine/command/network/network.yml
- internal/engine/command/phoenix/phoenix.gen.go
- internal/engine/command/voucher/voucher.gen.go
- internal/engine/command/voucher/voucher.yml
- internal/engine/engine.go
- internal/entity/user.go
- internal/generator/command.tmpl
- internal/repository/user_test.go
This PR ensure to check user role before executing a command.
> feat: check the userl role to execute commands

- internal/version/version.go
> chore: bump version to 0.5.0

- internal/engine/command/command.go
This PR adds user role to about and help command
> fix: add role to about and help commands

- internal/version/version.go
> chore: bump version to 0.6.0

- internal/engine/command/voucher/claim.go
This PR updates the error message for voucher code.
> chore: update error message

- internal/engine/engine.go
- internal/engine/engine_test.go
- internal/entity/application.go
- internal/platforms/telegram/telegram.go
- internal/platforms/whatsapp/whatsapp.go
> fix: find command by path
