- client/client_mgr.go
- discord/discord.go
> feat: network health command

- cmd/commands/repl.go
- cmd/commands/run.go
- config/config.go
- config/config_test.go
- discord/discord.go
- engine/commands/execute.go
- engine/engine.go
- engine/engine_test.go
- engine/interface.go
- wallet/wallet.go
This PR refactors the Bot Engine interface. The new interface has only one function named `Run`, it accpets input string and returns output as string.
- Fixes #(issue number)
> refactor(engine): refactor bot engine interface

- client/client_mgr.go
- engine/engine.go
- engine/engine_test.go
- store/interface.go
- store/mock.go
- store/store.go
- store/store_test.go
- store/test/store_example.json
- wallet/interface.go
- wallet/mock.go
- wallet/wallet.go
This PR replaces `sync.Map` with `map`, because Bot has concurrency guard.
> fix: make store in memory and file persistence

- engine/engine.go
- engine/engine_test.go
- engine/interface.go
- engine/run.go
- store/store_test.go
- store/test/.env.test
- utils/atomic_unit.go
- utils/atomic_unit_test.go
- wallet/interface.go
- wallet/mock.go
- wallet/wallet.go
> test: fixing failing tests, adding more engine tests

- discord/embeds.go
- discord/handlers.go
- engine/run.go
> fix: using InteractionRespond to respond to user interaction.

- cmd/discord/run.go
- config/config.go
- config/config_test.go
- config/global.go
- internal/engine/command/calculator/calculator.go
- internal/engine/command/command.go
- internal/engine/command/market/market.go
- internal/engine/command/market/price_test.go
- internal/engine/command/network/network.go
- internal/engine/command/network/status.go
- internal/engine/command/phoenix/phoenix.go
- internal/engine/command/voucher/voucher.go
- internal/engine/command/zealy/zealy.go
- internal/engine/engine.go
- internal/platforms/discord/discord.go
In this PR a new config field has been added to the separation of target network commands. With this feature we can deploy new instance of project for each network(test, main,..) without any confilict.
> feat(target flag): target mask config to separate networks commands 

- cmd/cli/main.go
- internal/delivery/grpc/robopac.go
- internal/delivery/http/http.go
- internal/engine/engine.go
- internal/platforms/discord/discord.go
- internal/platforms/telegram/telegram.go
input commands and arguments are now separated in commandHandler to avoid fault parsing error. In this PR commands are parsed into []string not map[string].
> fix(command): separate args and commands in commandHandler method

- config/config.go
- config/config.sample.yml
- config/global.go
- config/wallet.sample.neutered
- deployment/Dockerfile
- deployment/deploy.sh
- deployment/docker-compose.yml
- internal/engine/command/calculator/calculator.go
- internal/engine/command/command.go
- internal/engine/command/market/market.go
- internal/engine/command/phoenix/phoenix.go
- internal/engine/command/voucher/voucher.go
- internal/engine/command/zealy/zealy.go
- internal/engine/engine.go
- internal/platforms/discord/discord.go
- internal/platforms/telegram/telegram.go
- pkg/wallet/wallet.go
This PR refactors the deployments.
> ci: refacor deployment

- deployment/Dockerfile
- deployment/docker-compose.yml
This PR adds an extra host, `host.docker.internal`, for Docker containers and also adds `pagu-cli` to the Dockerfile.
Some explanatory links:
- https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach
- https://dev.to/mjnaderi/accessing-host-services-from-docker-containers-1a97
> ci: add extra host to composer

- internal/engine/engine.go
- internal/platforms/discord/discord.go
This PR fixes an issue where the command name is repeated instead of using the sub-command name. For example:  
`calculate calculate --stake=1000.0000000000 --days=1`  
should be:  
`calculate reward --stake=1000.0000000000 --days=1`
> fix: ensure set propoer sub-command name

- version.go
Bumping Pagu version after releasing latest stable one
> chore: bump version to 0.0.2

- internal/engine/engine.go
- internal/repository/user.go
- internal/repository/user_test.go
This PR adds debug lines for User query to investigate issue we have on production.
This will be reverted soon.
Related to #225
> chore: add debug line for user query

- internal/engine/engine.go
- internal/engine/engine_test.go
This PR fixes the issue where arguments have spaces inside the value part.
- Fixes #245
> fix: parse arguments with spaces

- internal/engine/command/command.go
- internal/engine/command/crowdfund/crowdfund.go
- internal/platforms/discord/discord.go
Choices value represented as string.
> fix: use choice value as string

- internal/engine/command/command.go
- internal/engine/command/crowdfund/claim.go
- internal/engine/command/crowdfund/crowdfund.gen.go
- internal/engine/command/crowdfund/crowdfund.go
- internal/engine/command/crowdfund/crowdfund.yml
- internal/engine/command/crowdfund/crowdfund_test.go
- internal/engine/command/crowdfund/purchase.go
- internal/entity/crowdfund.go
- internal/repository/crowdfund.go
- pkg/amount/amount.go
- pkg/amount/amount_test.go
- pkg/nowpayments/nowpayments.go
- pkg/wallet/interface.go
- pkg/wallet/mock.go
- pkg/wallet/wallet.go
Add crowdfund/calim command.
- Fixes #187
> feat: add crowdfund/claim command

- config/config.go
- config/config.sample.yml
- pkg/wallet/wallet.go
Ensure transaction fee set properly. It set to zero in some occasions.
> fix: set wallet fee

- config/global.go
- internal/platforms/discord/discord.go
- internal/platforms/telegram/telegram.go
Ensure moderator commands won't be deployed on mainnet bots
> fix: target name for Discord/Telegram bots

- internal/engine/command/command.go
Use ” ([double prime](https://symbl.cc/en/02BA/)) instead ` ([Letter Grave](https://symbl.cc/en/02CB/)) for making block code
> fix: use backticks for templates

- internal/engine/command/crowdfund/crowdfund.gen.go
- internal/engine/command/crowdfund/crowdfund.yml
- internal/engine/command/voucher/voucher.gen.go
- internal/engine/command/voucher/voucher.yml
- Moderator commands shouldn't be in any other bots than moderator bot.
- Some bot IDs were duplicated in YML files
https://github.com/pagu-project/pagu/issues/229
> fix: avoid mapping moderator commands in discord bot

- internal/engine/command/crowdfund/crowdfund.gen.go
- internal/engine/command/crowdfund/crowdfund.yml
We received an error from Discord stating:  
```
Required options must be placed before non-required options  
```  
This PR ensures that required options are placed before non-required ones in the `crowdfunding/edit` command.
> fix(discord): put required option before non-required ones

- .github/workflows/linting.yml
- .golangci.yml
- Makefile
This PR updates the [Golangci](https://golangci-lint.run/) to version 2.
> chore: update golangci linters
